apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  namespace: istio-system
  name: ingress-plb-config
spec:
  profile: empty # Do not install CRDs or the control plane - https://istio.io/latest/docs/setup/additional-setup/config-profiles
  components:
    ingressGateways:
      - name: ingressgateway
        enabled: true
        namespace: istio-ingress-public
        label:
          istio: ingressgateway
