apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  namespace: istio-system
  name: istio-base-install
spec:
  profile: minimal # Install control plane only without any gateways - https://istio.io/latest/docs/setup/additional-setup/config-profiles
  hub: docker.io/istio
  tag: 1.13.3
